Write a Python Program to find sum of array?

In [4]:
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import numpy as np

In [6]:
a = np.arange(25)
b = 0
for i in a:
  b = b + i
print(b)

300


Write a Python Program to find largest element in an array?

In [7]:
a = np.random.randint(1,500,25)
print(a)
high = 0
for i in a:
  if i>high:
    high = i
  else: 
    high 
print(high)

[331 192 122 173 291 195 380 466 366 333 241 158  40 203 433 417 315  71
 270  45  40  92 320 485 413]
485


Write a Python Program for array rotation?

In [162]:
def rotateArray(a,d):
    temp = []
    n=len(a)
    for i in range(d,n):
        temp.append(a[i])
    for i in range (0,d):
        temp.append(a[i])
    a=temp.copy()
    return temp
 
arr = np.random.randint(1,500,5)
print(arr)
print("Array after left rotation is: ", end=' ')
print(rotateArray(arr, 2))

[225 455 151 417  98]
Array after left rotation is:  [151, 417, 98, 225, 455]


Write a Python Program to Split the array and add the first part to the end?

In [151]:
def array_split(a,n,k):
    for i in range(0, k): 
      print(i)
      x = arr[0]
      for j in range(0, n-1):
        print(f' j= {j} and {a[j]}')
        arr[j] = arr[j + 1]
          
      arr[n-1] = x
          
  
arr = np.random.randint(1,25,5)
print(arr)
n = len(arr)
position = 2
  
array_split(arr, n, position)
  
for i in range(0, n): 
    print(arr[i],end =' ')

[ 4 23  8 12 15]
0
 j= 0 and 4
 j= 1 and 23
 j= 2 and 8
 j= 3 and 12
1
 j= 0 and 23
 j= 1 and 8
 j= 2 and 12
 j= 3 and 15
8 12 15 4 23 

In [114]:
a = [1,3,4,5,6,8]
temp = []
print(type(temp))
for i in a:
  if i<4:
    temp.append(i)
print(temp)
  



[1, 3]
[1, 3, 4, 5, 6, 8]


Write a Python Program to check if given array is Monotonic?

In [76]:
def ismonotonic(a,n):
  return ((all(a[i+1] >= a[i] for i in range(n-1))) or 
          (all(a[i+1] <= a[i] for i in range(n-1))))

   

In [77]:
a = np.random.randint(1,50,10)
print(a,len(a))
ismonotonic(a,len(a))

[21 32 32  7 40  4  3  1  8 18] 10


False