Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
a = np.random.rand(3,3)
b = np.random.rand(3,3)
print(a,'\n','\n',b,'\n','\n', a+b)

[[0.87333536 0.38798478 0.76039922]
 [0.51901328 0.85885027 0.23587753]
 [0.67677195 0.49344581 0.75097023]] 
 
 [[0.13152484 0.61379665 0.8295602 ]
 [0.84453113 0.52706215 0.06366278]
 [0.15948545 0.86843856 0.93749523]] 
 
 [[1.00486021 1.00178144 1.58995942]
 [1.36354441 1.38591242 0.29954031]
 [0.8362574  1.36188437 1.68846546]]


Write a Python Program to Multiply Two Matrices?

In [2]:
a = np.random.rand(3,3)
b = np.random.rand(3,3)
print(f'matrix 1 \n {a}\n \n matrix 2 \n{b} \n \n == \n{a@b}')

matrix 1 
 [[0.46791461 0.55161924 0.80137952]
 [0.45281151 0.85644444 0.4576188 ]
 [0.01205356 0.56096941 0.2750591 ]]
 
 matrix 2 
[[0.94118203 0.81839662 0.86837132]
 [0.71334113 0.28691182 0.19438082]
 [0.15307607 0.53729163 0.33834911]] 
 
 == 
[[0.95655755 0.97178033 0.78469388]
 [1.10716559 0.8621782  0.71451982]
 [0.45361212 0.3186003  0.21257467]]


Write a Python Program to Transpose a Matrix?

In [3]:
a = np.random.rand(3,3)
print(a)
Transpoe_mtarix = a.transpose()
print(f'Transformed matrix \n {Transpoe_mtarix}')

[[0.1731235  0.58160377 0.69946034]
 [0.11229236 0.50437174 0.05062779]
 [0.8820421  0.22137615 0.77266702]]
Transformed matrix 
 [[0.1731235  0.11229236 0.8820421 ]
 [0.58160377 0.50437174 0.22137615]
 [0.69946034 0.05062779 0.77266702]]


Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
S = 'Python Program to Sort Words in Alphabetic Order'
s = S.lower()
a = s.split()  
a.sort()
print('The sorted words are:')
for i in a:
    print(i)

The sorted words are:
alphabetic
in
order
program
python
sort
to
words


Write a Python Program to Remove Punctuation From a String?

In [5]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
a = ' Punctuation&@! in the s@tring!!!'
newstring = ''
for i in a:
    if i not in punctuations:
        newstring = newstring + i
print(newstring)

 Punctuation in the string
